-- Add missing EmailCommandType enum values
-- PUBLISH_HOUSING_UNIT, WANTED_COMMERCIAL, WANTED_SHARED_OWNERSHIP were missing

-- Add PUBLISH_HOUSING_UNIT
ALTER TYPE "EmailCommandType" ADD VALUE IF NOT EXISTS 'PUBLISH_HOUSING_UNIT';

-- Add WANTED_COMMERCIAL (if not exists)
ALTER TYPE "EmailCommandType" ADD VALUE IF NOT EXISTS 'WANTED_COMMERCIAL';

-- Add WANTED_SHARED_OWNERSHIP (if not exists)
ALTER TYPE "EmailCommandType" ADD VALUE IF NOT EXISTS 'WANTED_SHARED_OWNERSHIP';
